### ISSUE TITLE
Randomized Seed - Multiworld Crash

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Roman971/OoT-Randomizer#16]
Entrance placement attempt count exceeded for world 0
Traceback (most recent call last):
  File "D:\Games\Emulators\Nintendo 64\Tools\Romans\OoT-Randomizer\OoTRandomizer.py", line 61, in start
    main(settings)
  File "D:\Games\Emulators\Nintendo 64\Tools\Romans\OoT-Randomizer\Main.py", line 95, in main
    spoiler = generate(settings, window)
  File "D:\Games\Emulators\Nintendo 64\Tools\Romans\OoT-Randomizer\Main.py", line 148, in generate
    set_entrances(worlds)
  File "D:\Games\Emulators\Nintendo 64\Tools\Romans\OoT-Randomizer\EntranceShuffle.py", line 324, in set_entrances
    shuffle_random_entrances(worlds)
  File "D:\Games\Emulators\Nintendo 64\Tools\Romans\OoT-Randomizer\EntranceShuffle.py", line 428, in shuffle_random_entrances
    shuffle_entrance_pool(world, worlds, entrance_pool, one_way_target_entrance_pools[pool_type], locations_to_ensure_reachable, check_all=True)
  File "D:\Games\Emulators\Nintendo 64\Tools\Romans\OoT-Randomizer\EntranceShuffle.py", line 503, in shuffle_entrance_pool
    raise EntranceShuffleError('Entrance placement attempt count exceeded for world %d' % entrance_pool[0].world.id)
EntranceShuffle.EntranceShuffleError: Entrance placement attempt count exceeded for world 0

**Comment by P3rf3ctXZer0** [comment]
[2020-03-21 01-19-55.log](https://github.com/Roman971/OoT-Randomizer/files/4362515/2020-03-21.01-19-55.log)

**Comment by P3rf3ctXZer0** [comment]
![nqTehNu](https://user-images.githubusercontent.com/10351221/77220900-afb9e380-6b12-11ea-9cbe-b00b28a1ca54.jpg)

**Comment by Roman971** [comment]
Sorry for the late answer, I haven't really had time to work on randomizer dev lately.
This kind of error can show up randomly and almost always just means you should retry more seeds, to give the program more chances to generate a good one.

**Comment by P3rf3ctXZer0** [comment]
Oh I understand and thanks for the heads-up.
