### ISSUE TITLE
[Error] Triforce hunt crash

### ISSUE THREAD

**Issue by resinate** [Roman971/OoT-Randomizer#3]
'Triforce Piece'
Traceback (most recent call last):
  File "L:\N64\Tools\OoT-Random-11-4-19\OoTRandomizer.py", line 72, in start
    main(settings)
  File "L:\N64\Tools\OoT-Random-11-4-19\Main.py", line 88, in main
    spoiler = generate(settings, window)
  File "L:\N64\Tools\OoT-Random-11-4-19\Main.py", line 137, in generate
    settings.distribution.configure_triforce_hunt(worlds)
  File "L:\N64\Tools\OoT-Random-11-4-19\Plandomizer.py", line 661, in configure_triforce_hunt
    world.triforce_count = world.distribution.item_pool['Triforce Piece'].count
KeyError: 'Triforce Piece'

line links back to
world.triforce_count = world.distribution.item_pool['Triforce Piece'].count

**Comment by Roman971** [comment]
I believe this should now only happen if you try generating a Triforce Hunt seed with a plando file indicating a count of 0 "Triforce Pieces" in the item pool, which would fail anyway, so I'm closing this for now.
