### ISSUE TITLE
Can't generate seed with particular settings on 6.0.85 R-1

### ISSUE THREAD

**Issue by xlogisticsx** [Roman971/OoT-Randomizer#54]
AJJWKCDVKAB8PMAA243MR8TSAWCHGSKSTAUS6B7TDD8VGZPKASAJADABNAENBQ2EJTLAD9UC3JHLUVNFBSNCAASGSEFAB

Using the string above with no seed set, I get error the error below. 

Entrance placement attempt count exceeded for world 0
Traceback (most recent call last):
  File "F:\OOTR\OoT-Randomizer-Dev-R\OoTRandomizer.py", line 62, in start
    main(settings)
  File "F:\OOTR\OoT-Randomizer-Dev-R\Main.py", line 56, in main
    spoiler = generate(settings, window=window)
  File "F:\OOTR\OoT-Randomizer-Dev-R\Main.py", line 121, in generate
    worlds = build_world_graphs(settings, window=window)
  File "F:\OOTR\OoT-Randomizer-Dev-R\Main.py", line 168, in build_world_graphs
    set_entrances(worlds)
  File "F:\OOTR\OoT-Randomizer-Dev-R\EntranceShuffle.py", line 362, in set_entrances
    shuffle_random_entrances(worlds)
  File "F:\OOTR\OoT-Randomizer-Dev-R\EntranceShuffle.py", line 517, in shuffle_random_entrances
    shuffle_entrance_pool(world, worlds, entrance_pool, target_entrance_pools[pool_type], locations_to_ensure_reachable)
  File "F:\OOTR\OoT-Randomizer-Dev-R\EntranceShuffle.py", line 604, in shuffle_entrance_pool
    raise EntranceShuffleError('Entrance placement attempt count exceeded for world %d' % entrance_pool[0].world.id)
EntranceShuffle.EntranceShuffleError: Entrance placement attempt count exceeded for world 0

However, I turned off cow shuffle, settings string AJJWKCDVKAB8PMAA2L3MR8TSAWCHGSKSTAUS6B7TDD8VGZPKASAJADABNAENBQ2EJTLAD9UC3JHLUVNFBSNCAASGSEFAB, and it worked just fine.

**Comment by xlogisticsx** [comment]
Did a little more testing, and it seems that you just can't have all entrances for mixed pools plus cows. It works fine with only indoor entrances for mixed pools.

**Comment by Roman971** [comment]
Thanks for the report. It looks like this is still an issue in the latest version, tho it seems possible to generate seeds with these settings, it's just very unlikely and might take a lot of attemps. Nonetheless, It's not intended and I'll try to investigate it when I have time.
